name: Build Library
on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    name: build-linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: gerlero/add-apt-repository@v1
      with:
          uri: https://packagecloud.io/dcommander/libjpeg-turbo/any/
          key: https://packagecloud.io/dcommander/libjpeg-turbo/gpgkey
          suite: any
    - uses: gerlero/apt-install@v1
      with:
        packages: build-essential libhwy-dev liblcms2-dev libjpeg-turbo8-dev libpng-dev cmake libjpeg-dev zlib1g-dev libgif-dev
    - name: Build
      run: bash build_shared_library.sh
    - uses: actions/upload-artifact@v4
      with:
        name: ssimulacra2-linux
        path: ./build/**/*.*