name: Build Library
on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    name: build-linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get install build-essential libhwy-dev liblcms2-dev libjpeg62-turbo-dev libpng-dev cmake ninja-build
    - name: Build
      run: bash build_ssimulacra
    - uses: actions/upload-artifact@v4
      with:
        name: ssimulacra2-linux
        path: ./ssimulacra2